name: tezal
description: mobile project for tezal market

# Flutter: build-name    **  Android: versionName  **  Ios: CFBundleShortVersionString
# Flutter: build-number  **  Android: versionCode  **  Ios: CFBundleVersion
# ------------------------------------------------------------------------------------
# Flutter Version Number is: build-name + build-number
# ----------------------------------------------------
version: 1.0.0+1

# Dart sdk version
# ----------------
environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  # used to: functional programming in dart
  dartz: ^0.9.2
  # used to: provide app's dir path
  path_provider: ^2.0.1
  # used to: routing service
  sailor: ^0.7.1
  # used to: css form widget styling
  division: ^0.8.8
  # used to: http services
  dio: ^4.0.0
  http: ^0.13.1
  retrofit: ^2.0.0-beta1
  data_connection_checker: ^0.3.4
  # used to: state management
  provider: ^5.0.0
  # used to: service locator
  get: ^4.1.4
  # used to: launch urls
  url_launcher: ^5.7.10
  # used to: access location service
  geolocator: ^6.1.14
  google_maps_flutter: ^2.0.3
  google_map_location_picker: ^4.1.7
  # used to: local storage
  flutter_secure_storage: ^3.3.4
  # used to: pre made icons pack
  flutter_icons: ^1.1.0
  # used to: show html tags
  flutter_html: ^0.11.1
  # used to: generate app's launcher icon
  flutter_launcher_icons: ^0.9.0
  # used to: show video format file
  video_player: ^2.1.1
  # used to: pick image from grallery
  image_picker: ^0.7.4
  # used to: avoiding hide keyboard
  keyboard_avoider: ^0.1.2
  # used to: pin code fields
  pin_code_text_field: ^1.7.1
  # used to: cache images in offline mode
  cached_network_image: ^2.5.1
  # used to: loading
  progress_dialog: ^1.2.4
  flutter_spinkit: ^4.1.2+1
  # used to: currency format
  intl: ^0.17.0
  # used to: restart services
  # flutter_phoenix: ^1.0.0
  # used to: access user contacts
  flutter_contacts: ^1.0.0
  # used to: tuple
  tuple: ^2.0.0
  # used to: to access app version
  package_info: ^2.0.0
  # used to: build
  build: ^2.0.0

dependency_overrides:
  tuple: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  retrofit_generator: ^2.0.0-beta1
  build_runner: ^1.11.1

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/ic_launcher.png"

flutter:
  # access to material icons and elements need to this package
  #  ---------------------------------------------------------
  uses-material-design: true

  # application assets part
  #  ----------------------
  assets:
    - assets/
    - assets/videos/
    - assets/images/
    - assets/vectors/
    - assets/langs/fa.json
    - assets/langs/en.json
    - assets/map_style.txt

  #  application fonts part
  #  ----------------------
  fonts:
    - family: Yekan
      fonts:
        - asset: assets/fonts/danafanumregular.ttf
          weight: 500
        - asset: assets/fonts/danafanummedium.ttf
          weight: 700
        - asset: assets/fonts/danafanumbold.ttf
          weight: 900
