name: tezal
description: mobile project for tezal market

# Flutter: build-name    **  Android: versionName  **  Ios: CFBundleShortVersionString
# Flutter: build-number  **  Android: versionCode  **  Ios: CFBundleVersion
# ------------------------------------------------------------------------------------
# Flutter Version Number is: build-name + build-number
# ----------------------------------------------------
version: 1.0.0+1

# Dart sdk version
# ----------------
environment:
  sdk: ">=2.8.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  # used to: functional programming in dart
  dartz: ^0.9.2
  # used to: provide app's dir path
  path_provider: ^1.6.10
  # used to: routing service
  sailor: ^0.7.1
  # used to: css form widget styling
  division: ^0.8.8
  # used to: http services
  dio: ^3.0.10
  http: ^0.12.2
  retrofit: ^1.3.4+1
  data_connection_checker: ^0.3.4
  # used to: use json serialization
  json_annotation: ^3.1.1
  json_serializable: ^3.5.1
  # used to: state management
  provider: ^4.3.3
  # used to: lauche urls
  url_launcher: ^5.7.10
  # used to: access location service
  map: ^0.2.0+1
  latlng: ^0.0.2
  geolocator: ^6.1.13
  maps_launcher: ^1.2.2+2
  flutter_map: ^0.10.1+1
  google_maps_flutter: ^1.1.1
  location_permissions: ^3.0.0+1
  permission_handler: ^5.1.0+2
  permission: ^0.1.7
  # used to: local storage
  shared_preferences: ^0.5.12+4
  flutter_secure_storage: ^3.3.5
  # used to: premaded icons pack
  flutter_icons: ^1.1.0
  cupertino_icons: ^1.0.0
  # used to: generate app's launcher icon
  flutter_launcher_icons: ^0.8.1
  # used to: avoiding hide keyboard
  keyboard_avoider: ^0.1.2
  # used to: pin code fields
  pin_code_text_field: ^1.7.1
  # used to: cache images in offline mode
  cached_network_image: ^2.5.1
  # used to: loading
  progress_dialog: ^1.2.4
  flutter_spinkit: ^4.1.2+1
  # used to: validate email address
  email_validator: '^1.0.0'
  # used to: carousel slider
  carousel_slider: ^2.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  retrofit_generator: ^1.4.1+3
  build_runner: ^1.11.1

# flutter_icons:
#   android: "launcher_icon"
#   ios: true
#   image_path: "assets/ic_launcher_1.png"

flutter:
  # access to material icons and elements need to this package
  #  ---------------------------------------------------------
  uses-material-design: true

  # application assets part
  #  ----------------------
  assets:
    - assets/
    - lang/fa.json
    - lang/en.json

  #  application fonts part
  #  ----------------------
  fonts:
    - family: Yekan
      fonts:
        - asset: fonts/Yekan.ttf


